## 0. pip install

In [1]:
pip install pyodbc pandas python-dotenv

Requirement already satisfied: pyodbc in c:\Anaconda\Lib\site-packages (5.3.0)
Requirement already satisfied: pandas in c:\Anaconda\Lib\site-packages (3.0.0)
Requirement already satisfied: python-dotenv in c:\Anaconda\Lib\site-packages (1.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\Anaconda\Lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Anaconda\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Anaconda\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Anaconda\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~penai (c:\Anaconda\Lib\site-packages)
WARNING: Ignoring invalid distribution ~penai (c:\Anaconda\Lib\site-packages)
WARNING: Ignoring invalid distribution ~penai (c:\Anaconda\Lib\site-packages)

ODBC Driver 17 for SQL Server 확인

In [1]:
import pyodbc

pyodbc.drivers()

['SQL Server',
 'ODBC Driver 17 for SQL Server',
 'Microsoft Access Driver (*.mdb, *.accdb)',
 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)',
 'Microsoft Access Text Driver (*.txt, *.csv)',
 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

## 1. connect Agora Warehous

In [2]:
import pyodbc
import pandas as pd

SERVER = "6orm62c43rguff2mpdxwqy76tu-3meqk2mii2pehfjxfscngx5a6e.datawarehouse.fabric.microsoft.com"

conn_str = f"""
DRIVER={{ODBC Driver 17 for SQL Server}};
SERVER={SERVER},1433;
Encrypt=yes;
TrustServerCertificate=no;
Authentication=ActiveDirectoryInteractive;
Connection Timeout=30;
"""

conn = pyodbc.connect(conn_str)

df = pd.read_sql("SELECT DB_NAME() AS current_db", conn)
df

C:\Users\LouisLee(이시호)\AppData\Local\Temp\ipykernel_6708\3858062543.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT DB_NAME() AS current_db", conn)

                  current_db
0  DataflowsStagingLakehouse

In [4]:
df_db = pd.read_sql("""
SELECT * FROM TMKR_L.dbo.l_co_users
WHERE dept_cd = 'DT30106'
""", conn)

df_db

C:\Users\LouisLee(이시호)\AppData\Local\Temp\ipykernel_6708\2263754774.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_db = pd.read_sql("""

,user_id,group_id,dept_cd,showroom_id,name,title,biz_charge,zip,addr,addr_no,...,first_name_eng,sms_default_no,layoff_dt,resume_dt,reactive_yn,bi_code,edu_primary_yn,device_yn,regi_no_dec,ELT_TIME
0,DT1106,DT00000,DT30106,NaN,이민균,03,NaN,05649,서울 송파구 오륜동,올림픽선수촌아파트 253동 1401호,...,NaN,NaN,None,None,None,None,NaN,None,Encrypted,2026-06-22T11:06:16.2426485Z
1,DT0005,DT00000,DT30106,NaN,김찬규,06,NaN,10507,경기 고양시 덕양구 토당동,99-39 장미아파트 나동 401,...,NaN,NaN,None,None,None,None,NaN,None,Encrypted,2026-06-22T11:06:16.2426485Z
2,DT0406,DT00000,DT30106,01,윤희기,03,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,NaN,None,Encrypted,2026-06-22T11:06:16.2426485Z
3,DT0302,DT00000,DT30106,01,서광현,04,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,NaN,None,Encrypted,2026-06-22T11:06:16.2426485Z
4,DT0808,DT00000,DT30106,NaN,인제섭,02,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,NaN,None,Encrypted,2026-06-22T11:06:16.2426485Z
5,DT0811,DT00000,DT30106,NaN,손형문,02,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,NaN,None,Encrypted,2026-06-22T11:06:16.2426485Z
6,DT0915,DT00000,DT30106,NaN,박민철,03,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,NaN,None,Encrypted,2026-06-22T11:06:16.2426485Z
7,DT0827,DT00000,DT30106,NaN,김재용,03,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,NaN,None,Encrypted,2026-06-22T11:06:16.2426485Z
8,DT0909,DT00000,DT30106,NaN,김창근,04,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,NaN,None,Encrypted,2026-06-22T11:06:16.2426485Z
9,DT0627,DT00000,DT30106,01,김현성,04,영업,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,NaN,None,Encrypted,2026-06-22T11:06:16.2426485Z
10,DT0820,DT00000,DT30106,NaN,박성민,03,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,NaN,None,NaN,2026-06-22T11:06:16.2426485Z
11,DT0004,DT00000,DT30106,NaN,신동경,06,NaN,NaN,NaN,NaN,...,SHIN,NaN,None,None,None,None,NaN,None,NaN,2026-06-22T11:06:16.2426485Z
12,DT0509,DT00000,DT30106,01,유강우,03,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,NaN,None,Encrypted,2026-06-22T11:06:16.2426485Z
13,DT0006,DT00000,DT30106,01,이한백,06,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,NaN,None,Encrypted,2026-06-22T11:06:16.2426485Z
14,DT1500,DT00000,DT30106,NaN,신준철,02,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,NaN,None,Encrypted,2026-06-22T11:06:16.2426485Z
15,DT1701,DT00000,DT30106,NaN,전한수,03,NaN,NaN,NaN,NaN,...,JEON,NaN,None,None,None,None,NaN,None,NaN,2026-06-22T11:06:16.2426485Z
16,DT1920,DT00000,DT30106,NaN,이민균,05,NaN,NaN,NaN,NaN,...,LEE,01053019725,None,None,None,None,Y,None,NaN,2026-06-22T11:06:16.2426485Z
17,DT2334,DT00000,DT30106,NaN,최충익,03,NaN,NaN,NaN,NaN,...,CHOI,NaN,None,None,None,None,Y,None,NaN,2026-06-22T11:06:16.2426485Z
18,DT1654,DT00000,DT30106,NaN,윤성환,04,NaN,NaN,NaN,NaN,...,YOON,NaN,None,None,None,None,NaN,None,NaN,2026-06-22T11:06:16.2426485Z
19,DT2138,DT00000,DT30106,NaN,김태훈,04,NaN,NaN,NaN,NaN,...,KIM,NaN,None,None,None,None,NaN,None,NaN,2026-06-22T11:06:16.2426485Z
20,DT1702,DT00000,DT30106,NaN,남영준,03,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,NaN,None,NaN,2026-06-22T11:06:16.2426485Z
21,DT1203,DT00000,DT30106,NaN,박혁수,04,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,NaN,None,NaN,2026-06-22T11:06:16.2426485Z
22,DT1122,DT00000,DT30106,NaN,김기범,03,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,NaN,None,NaN,2026-06-22T11:06:16.2426485Z
23,DT1205,DT00000,DT30106,NaN,한승훈,05,NaN,NaN,NaN,NaN,...,HAN,NaN,None,None,None,None,Y,None,NaN,2026-06-22T11:06:16.2426485Z
24,DT2529,DT00000,DT30106,NaN,최윤석2,03,NaN,NaN,NaN,NaN,...,CHOI,NaN,None,None,None,None,Y,None,NaN,2026-06-22T11:06:16.2426485Z
25,DT2136,DT00000,DT30106,NaN,김태균,04,NaN,NaN,NaN,NaN,...,KIM,NaN,None,None,None,None,Y,None,NaN,2026-06-22T11:06:16.2426485Z
26,DT2209,DT00000,DT30106,NaN,김영서,03,NaN,NaN,NaN,NaN,...,KIM,NaN,None,None,None,None,Y,None,NaN,2026-06-22T11:06:16.2426485Z
27,DT1208,DT00000,DT30106,NaN,이순우,02,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,NaN,None,NaN,2026-06-22T11:06:16.2426485Z
28,DT1722,DT00000,DT30106,NaN,김동환,02,NaN,NaN,NaN,NaN,...,NaN,NaN,None,None,None,None,NaN,None,NaN,2026-06-22T11:06:16.2426485Z

In [5]:
df_db = pd.read_sql("""
SELECT TOP 100 * FROM TMKR_L.dbo.l_svc_propo
WHERE shop_cd = 'DT30106'
""", conn)

df_db

C:\Users\LouisLee(이시호)\AppData\Local\Temp\ipykernel_6708\2269127176.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_db = pd.read_sql("""

,shop_cd,propo_dt,propo_seq,repair_type_cd,propo_type_cd,vin,vis,vehic_no1,vehic_no2,variant_nm,...,propo_talk_send_time,propo_talk_send_user_id,propo_talk_mseq,calc_talk_send_time,calc_talk_send_user_id,calc_talk_mseq,cust_repair_req_text,sign_yn,agora_use_dt,ELT_TIME
0,DT30106,20250916,362.0,2,1,JTHKD5BH2J2333253,J2333253,64거,5618,CT200h,...,None,None,None,None,None,None,None,Y,2025-09-22 20:06:09,2025-09-23T07:01:12.6153443Z
1,DT30106,20250916,366.0,1,1,JTHKD5BH2J2333253,J2333253,64거,5618,CT200h,...,None,None,None,None,None,None,None,Y,2025-09-22 20:06:09,2025-09-23T07:01:12.6153443Z
2,DT30106,20250922,476.0,2,1,JTHB21B14K2027531,K2027531,31가,5984,ES300h,...,None,None,None,None,None,None,None,Y,2025-09-22 20:12:57,2025-09-23T07:01:12.6153443Z
3,DT30106,20250922,488.0,1,1,JTHBW1GG0G2110544,G2110544,31수,0994,ES300h,...,None,None,None,None,None,None,None,Y,2025-09-22 20:10:29,2025-09-23T07:01:12.6153443Z
4,DT30106,20250912,295.0,2,1,JTHBA1C18N2010558,N2010558,172수,6622,ES300h(N),...,None,None,None,None,None,None,None,Y,2025-09-22 17:19:50,2025-09-22T18:39:17.513702Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,DT30106,20250922,479.0,1,1,JTHYBJAH8S2011003,S2011003,108가,5044,UX300h,...,None,None,None,None,None,None,None,Y,2025-09-22 11:42:50,2025-09-22T18:39:17.513702Z
96,DT30106,20250922,502.0,NaN,NaN,JTHBW1GG9H2147044,H2147044,62조,4539,ES300h,...,None,None,None,None,None,None,None,N,2025-09-22 16:07:05,2025-09-22T18:39:17.513702Z
97,DT30106,20250922,505.0,NaN,NaN,JTHBW1GG8H2157161,H2157161,01두,9021,ES300h,...,None,None,None,None,None,None,None,Y,2025-09-22 16:57:24,2025-09-22T18:39:17.513702Z
98,DT30106,20250922,508.0,NaN,NaN,JTHBW1GG8E2061655,E2061655,31머,9783,ES300h,...,None,None,None,None,None,None,None,Y,2025-09-22 17:44:26,2025-09-22T18:39:17.513702Z
99,DT30106,20241126,611.0,2,1,JTHB21B11K2058512,K2058512,23로,7593,ES300h,...,None,None,None,None,None,None,None,Y,2024-12-09 11:03:41.0000000,2025-03-16T22:13:04.0053911Z

### TMKR_L

In [25]:
import pyodbc
import pandas as pd

SERVER = "6orm62c43rguff2mpdxwqy76tu-3meqk2mii2pehfjxfscngx5a6e.datawarehouse.fabric.microsoft.com"
DATABASE = "TMKR_L"

conn_str = f"""
DRIVER={{ODBC Driver 17 for SQL Server}};
SERVER={SERVER},1433;
DATABASE={DATABASE};
Encrypt=yes;
TrustServerCertificate=no;
Authentication=ActiveDirectoryInteractive;
Connection Timeout=30;
"""

conn = pyodbc.connect(conn_str)

df = pd.read_sql("SELECT DB_NAME() AS current_db", conn)
df

C:\Users\LouisLee(이시호)\AppData\Local\Temp\ipykernel_27032\839450372.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT DB_NAME() AS current_db", conn)

  current_db
0     TMKR_L

In [27]:
cursor = conn.cursor()
cursor.execute(f"USE [{DATABASE}]")
cursor.close()

tmkr_l_df = pd.read_sql("""
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
ORDER BY TABLE_SCHEMA, TABLE_NAME;
""", conn)

tmkr_l_df

C:\Users\LouisLee(이시호)\AppData\Local\Temp\ipykernel_27032\2884869036.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  tmkr_l_df = pd.read_sql("""

    TABLE_SCHEMA                       TABLE_NAME  TABLE_TYPE
0            dbo                         L_SVC_CR  BASE TABLE
1            dbo                         T_SVC_CR  BASE TABLE
2            dbo                          co_code  BASE TABLE
3            dbo                       co_company  BASE TABLE
4            dbo                         co_group  BASE TABLE
..           ...                              ...         ...
177          sys  managed_delta_table_checkpoints        VIEW
178          sys        managed_delta_table_forks        VIEW
179          sys    managed_delta_table_log_files        VIEW
180          sys             managed_delta_tables        VIEW
181          sys                   sys_dw_schemas        VIEW

[182 rows x 3 columns]

### TMKR_W

In [ ]:
import pyodbc
import pandas as pd

SERVER = "6orm62c43rguff2mpdxwqy76tu-3meqk2mii2pehfjxfscngx5a6e.datawarehouse.fabric.microsoft.com"
DATABASE = "TMKR_W"

conn_str = f"""
DRIVER={{ODBC Driver 17 for SQL Server}};
SERVER={SERVER},1433;
DATABASE={DATABASE};
Encrypt=yes;
TrustServerCertificate=no;
Authentication=ActiveDirectoryInteractive;
Connection Timeout=30;
"""

conn = pyodbc.connect(conn_str)

df = pd.read_sql("SELECT DB_NAME() AS current_db", conn)
df

C:\Users\LouisLee(이시호)\AppData\Local\Temp\ipykernel_27032\839450372.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT DB_NAME() AS current_db", conn)

  current_db
0     TMKR_L

In [28]:
cursor = conn.cursor()
cursor.execute(f"USE [{DATABASE}]")
cursor.close()

tmkr_w_df = pd.read_sql("""
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
ORDER BY TABLE_SCHEMA, TABLE_NAME;
""", conn)

tmkr_w_df

C:\Users\LouisLee(이시호)\AppData\Local\Temp\ipykernel_27032\681686325.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  tmkr_w_df = pd.read_sql("""

    TABLE_SCHEMA                       TABLE_NAME  TABLE_TYPE
0            dbo                         L_SVC_CR  BASE TABLE
1            dbo                         T_SVC_CR  BASE TABLE
2            dbo                          co_code  BASE TABLE
3            dbo                       co_company  BASE TABLE
4            dbo                         co_group  BASE TABLE
..           ...                              ...         ...
177          sys  managed_delta_table_checkpoints        VIEW
178          sys        managed_delta_table_forks        VIEW
179          sys    managed_delta_table_log_files        VIEW
180          sys             managed_delta_tables        VIEW
181          sys                   sys_dw_schemas        VIEW

[182 rows x 3 columns]

### TMKR_W_CUSTOMER

### TMKR_W_PARTS

In [29]:
import pyodbc
import pandas as pd

SERVER = "6orm62c43rguff2mpdxwqy76tu-3meqk2mii2pehfjxfscngx5a6e.datawarehouse.fabric.microsoft.com"
DATABASE = "TMKR_W_PARTS"

conn_str = f"""
DRIVER={{ODBC Driver 17 for SQL Server}};
SERVER={SERVER},1433;
DATABASE={DATABASE};
Encrypt=yes;
TrustServerCertificate=no;
Authentication=ActiveDirectoryInteractive;
Connection Timeout=30;
"""

conn = pyodbc.connect(conn_str)

df = pd.read_sql("SELECT DB_NAME() AS current_db", conn)
df

C:\Users\LouisLee(이시호)\AppData\Local\Temp\ipykernel_27032\813252050.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT DB_NAME() AS current_db", conn)

     current_db
0  TMKR_W_PARTS

In [30]:
cursor = conn.cursor()
cursor.execute(f"USE [{DATABASE}]")
cursor.close()

tmkr_w_parts_df = pd.read_sql("""
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
ORDER BY TABLE_SCHEMA, TABLE_NAME;
""", conn)

tmkr_w_parts_df

C:\Users\LouisLee(이시호)\AppData\Local\Temp\ipykernel_27032\2971069426.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  tmkr_w_parts_df = pd.read_sql("""

     TABLE_SCHEMA                        TABLE_NAME  TABLE_TYPE
0             dbo                      기준_데이터업데이트날짜  BASE TABLE
1             dbo                        기준_부품서비스센터  BASE TABLE
2             dbo                           기준_출고일자  BASE TABLE
3             dbo                     정보_부품출고제안서_v2  BASE TABLE
4   queryinsights             exec_requests_history        VIEW
5   queryinsights             exec_sessions_history        VIEW
6   queryinsights            frequently_run_queries        VIEW
7   queryinsights              long_running_queries        VIEW
8   queryinsights                 sql_pool_insights        VIEW
9             sys  dm_db_external_tables_log_status        VIEW
10            sys             external_delta_tables        VIEW
11            sys   managed_delta_table_checkpoints        VIEW
12            sys         managed_delta_table_forks        VIEW
13            sys     managed_delta_table_log_files        VIEW
14            sys              managed_delta_tables        VIEW
15            sys                    sys_dw_schemas        VIEW

### TMKR_W_PARTS(IMS)

In [23]:
import pyodbc
import pandas as pd

SERVER = "6orm62c43rguff2mpdxwqy76tu-3meqk2mii2pehfjxfscngx5a6e.datawarehouse.fabric.microsoft.com"
DATABASE = "TMKR_W_PARTS(IMS)"

conn_str = f"""
DRIVER={{ODBC Driver 17 for SQL Server}};
SERVER={SERVER},1433;
DATABASE={DATABASE};
Encrypt=yes;
TrustServerCertificate=no;
Authentication=ActiveDirectoryInteractive;
Connection Timeout=30;
"""

conn = pyodbc.connect(conn_str)

df = pd.read_sql("SELECT DB_NAME() AS current_db", conn)
df

C:\Users\LouisLee(이시호)\AppData\Local\Temp\ipykernel_27032\3962101568.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT DB_NAME() AS current_db", conn)

        current_db
0  TMKR_W_CUSTOMER

In [31]:
cursor = conn.cursor()
cursor.execute(f"USE [{DATABASE}]")
cursor.close()

tmkr_w_parts_ims_df = pd.read_sql("""
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
ORDER BY TABLE_SCHEMA, TABLE_NAME;
""", conn)

tmkr_w_parts_ims_df

C:\Users\LouisLee(이시호)\AppData\Local\Temp\ipykernel_27032\2950017268.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  tmkr_w_parts_ims_df = pd.read_sql("""

     TABLE_SCHEMA                        TABLE_NAME  TABLE_TYPE
0             dbo                      기준_데이터업데이트날짜  BASE TABLE
1             dbo                        기준_부품서비스센터  BASE TABLE
2             dbo                           기준_출고일자  BASE TABLE
3             dbo                     정보_부품출고제안서_v2  BASE TABLE
4   queryinsights             exec_requests_history        VIEW
5   queryinsights             exec_sessions_history        VIEW
6   queryinsights            frequently_run_queries        VIEW
7   queryinsights              long_running_queries        VIEW
8   queryinsights                 sql_pool_insights        VIEW
9             sys  dm_db_external_tables_log_status        VIEW
10            sys             external_delta_tables        VIEW
11            sys   managed_delta_table_checkpoints        VIEW
12            sys         managed_delta_table_forks        VIEW
13            sys     managed_delta_table_log_files        VIEW
14            sys              managed_delta_tables        VIEW
15            sys                    sys_dw_schemas        VIEW

### TMKR_W_SALES

In [33]:
import pyodbc
import pandas as pd

SERVER = "6orm62c43rguff2mpdxwqy76tu-3meqk2mii2pehfjxfscngx5a6e.datawarehouse.fabric.microsoft.com"
DATABASE = "TMKR_W_SALES"

conn_str = f"""
DRIVER={{ODBC Driver 17 for SQL Server}};
SERVER={SERVER},1433;
DATABASE={DATABASE};
Encrypt=yes;
TrustServerCertificate=no;
Authentication=ActiveDirectoryInteractive;
Connection Timeout=30;
"""

conn = pyodbc.connect(conn_str)

df = pd.read_sql("SELECT DB_NAME() AS current_db", conn)
df

C:\Users\LouisLee(이시호)\AppData\Local\Temp\ipykernel_27032\1312140838.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT DB_NAME() AS current_db", conn)

     current_db
0  TMKR_W_SALES

In [34]:
cursor = conn.cursor()
cursor.execute(f"USE [{DATABASE}]")
cursor.close()

tmkr_w_sales_df = pd.read_sql("""
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
ORDER BY TABLE_SCHEMA, TABLE_NAME;
""", conn)

tmkr_w_sales_df

C:\Users\LouisLee(이시호)\AppData\Local\Temp\ipykernel_27032\2374931223.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  tmkr_w_sales_df = pd.read_sql("""

     TABLE_SCHEMA                        TABLE_NAME  TABLE_TYPE
0             dbo                        기준_WSH_브랜치  BASE TABLE
1             dbo                      기준_계약_순번기준일시  BASE TABLE
2             dbo                         기준_계약_전시장  BASE TABLE
3             dbo                        기준_계약_차량사양  BASE TABLE
4             dbo                     기준_재고_PDI_PPO  BASE TABLE
5             dbo                        기준_재고_리콜내역  BASE TABLE
6             dbo                        기준_재고_배정내용  BASE TABLE
7             dbo                         기준_재고_브랜치  BASE TABLE
8             dbo                        기준_재고_차량사양  BASE TABLE
9             dbo                         기준일자_계약일자  BASE TABLE
10            dbo                         기준일자_입항일자  BASE TABLE
11            dbo                         기준일자_통관일자  BASE TABLE
12            dbo              정보_WholeSalesHistory  BASE TABLE
13            dbo                             정보_계약  BASE TABLE
14            dbo                           정보_차량재고  BASE TABLE
15            dbo                          최신업데이트날짜  BASE TABLE
16  queryinsights             exec_requests_history        VIEW
17  queryinsights             exec_sessions_history        VIEW
18  queryinsights            frequently_run_queries        VIEW
19  queryinsights              long_running_queries        VIEW
20  queryinsights                 sql_pool_insights        VIEW
21            sys  dm_db_external_tables_log_status        VIEW
22            sys             external_delta_tables        VIEW
23            sys   managed_delta_table_checkpoints        VIEW
24            sys         managed_delta_table_forks        VIEW
25            sys     managed_delta_table_log_files        VIEW
26            sys              managed_delta_tables        VIEW
27            sys                    sys_dw_schemas        VIEW

## 2. connect BP/KTWS

In [38]:
import pyodbc
import pandas as pd

SERVER = "6orm62c43rguff2mpdxwqy76tu-xhehnpiu2bautgglhximxpyqca.datawarehouse.fabric.microsoft.com"

conn_str = f"""
DRIVER={{ODBC Driver 17 for SQL Server}};
SERVER={SERVER},1433;
Encrypt=yes;
TrustServerCertificate=no;
Authentication=ActiveDirectoryInteractive;
Connection Timeout=30;
"""

conn = pyodbc.connect(conn_str)

df_db = pd.read_sql("""
SELECT name
FROM sys.databases
ORDER BY name
""", conn)

df_db

C:\Users\LouisLee(이시호)\AppData\Local\Temp\ipykernel_27032\2283993718.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_db = pd.read_sql("""

                                          name
0                    DataflowsStagingLakehouse
1                    DataflowsStagingWarehouse
2                                        KPI_L
3                                        KPI_W
4                                       master
5  StagingLakehouseForDataflows_20250812005148
6  StagingWarehouseForDataflows_20250812005211

In [37]:
import pyodbc
import pandas as pd

SERVER = "6orm62c43rguff2mpdxwqy76tu-xhehnpiu2bautgglhximxpyqca.datawarehouse.fabric.microsoft.com"
DATABASE = "KPI_L"

conn_str = f"""
DRIVER={{ODBC Driver 17 for SQL Server}};
SERVER={SERVER},1433;
DATABASE={DATABASE};
Encrypt=yes;
TrustServerCertificate=no;
Authentication=ActiveDirectoryInteractive;
Connection Timeout=30;
"""

conn = pyodbc.connect(conn_str)

df = pd.read_sql("SELECT DB_NAME() AS current_db", conn)
df

cursor = conn.cursor()
cursor.execute(f"USE [{DATABASE}]")
cursor.close()

kpi_l_df = pd.read_sql("""
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
ORDER BY TABLE_SCHEMA, TABLE_NAME;
""", conn)

kpi_l_df

C:\Users\LouisLee(이시호)\AppData\Local\Temp\ipykernel_27032\3609988323.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT DB_NAME() AS current_db", conn)
C:\Users\LouisLee(이시호)\AppData\Local\Temp\ipykernel_27032\3609988323.py:26: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  kpi_l_df = pd.read_sql("""

     TABLE_SCHEMA                        TABLE_NAME  TABLE_TYPE
0             dbo                     a_bilogo_pics  BASE TABLE
1             dbo                  a_bilogo_pics_v2  BASE TABLE
2             dbo                        co_company  BASE TABLE
3             dbo                 l_co_calendar_stg  BASE TABLE
4             dbo                         l_co_code  BASE TABLE
5             dbo                        l_co_group  BASE TABLE
6             dbo                 l_co_group_bi_stg  BASE TABLE
7             dbo                     l_co_holdings  BASE TABLE
8             dbo                 l_co_organization  BASE TABLE
9             dbo                        l_co_users  BASE TABLE
10            dbo                        l_co_vehic  BASE TABLE
11            dbo                         l_cu_base  BASE TABLE
12            dbo                       l_cu_detail  BASE TABLE
13            dbo                     l_om_contract  BASE TABLE
14            dbo                         l_pt_part  BASE TABLE
15            dbo                    l_pt_sout_detl  BASE TABLE
16            dbo               l_sfa_testcar_trial  BASE TABLE
17            dbo               l_sfa_testdrive_req  BASE TABLE
18            dbo                       l_svc_propo  BASE TABLE
19            dbo                  l_svc_propo_part  BASE TABLE
20            dbo                        l_vs_model  BASE TABLE
21            dbo                          l_vs_sfx  BASE TABLE
22            dbo                      l_vs_variant  BASE TABLE
23            dbo                 l_vt_vehic_supply  BASE TABLE
24            dbo                         t_co_code  BASE TABLE
25            dbo                        t_co_group  BASE TABLE
26            dbo                 t_co_group_bi_stg  BASE TABLE
27            dbo                     t_co_holdings  BASE TABLE
28            dbo                 t_co_organization  BASE TABLE
29            dbo                        t_co_users  BASE TABLE
30            dbo                        t_co_vehic  BASE TABLE
31            dbo                         t_cu_base  BASE TABLE
32            dbo                       t_cu_detail  BASE TABLE
33            dbo                     t_om_contract  BASE TABLE
34            dbo                         t_pt_part  BASE TABLE
35            dbo                    t_pt_sout_detl  BASE TABLE
36            dbo               t_sfa_testcar_trial  BASE TABLE
37            dbo               t_sfa_testdrive_req  BASE TABLE
38            dbo                       t_svc_propo  BASE TABLE
39            dbo                  t_svc_propo_part  BASE TABLE
40            dbo                        t_vs_model  BASE TABLE
41            dbo                          t_vs_sfx  BASE TABLE
42            dbo                      t_vs_variant  BASE TABLE
43            dbo                 t_vt_vehic_supply  BASE TABLE
44            dbo                   z_target_sample  BASE TABLE
45  queryinsights             exec_requests_history        VIEW
46  queryinsights             exec_sessions_history        VIEW
47  queryinsights            frequently_run_queries        VIEW
48  queryinsights              long_running_queries        VIEW
49  queryinsights                 sql_pool_insights        VIEW
50            sys  dm_db_external_tables_log_status        VIEW
51            sys             external_delta_tables        VIEW
52            sys   managed_delta_table_checkpoints        VIEW
53            sys         managed_delta_table_forks        VIEW
54            sys     managed_delta_table_log_files        VIEW
55            sys              managed_delta_tables        VIEW
56            sys                    sys_dw_schemas        VIEW

## 3. connect Karete

In [ ]:
import pyodbc
import pandas as pd

SERVER = "6orm62c43rguff2mpdxwqy76tu-kp6lscr4iunung5p66mov6kcka.datawarehouse.fabric.microsoft.com"

conn_str = f"""
DRIVER={{ODBC Driver 17 for SQL Server}};
SERVER={SERVER},1433;
Encrypt=yes;
TrustServerCertificate=no;
Authentication=ActiveDirectoryInteractive;
Connection Timeout=30;
"""

conn = pyodbc.connect(conn_str)

df_db = pd.read_sql("""
SELECT name
FROM sys.databases
ORDER BY name
""", conn)

df_db